BDIR := bin
ODIR := obj
SDIR := src
PKGS := llvm

CAMLF := ocamlfind ocamlc
CAMLLEX := $(CAMLLEX) 
CAMLYACC := ocamlyacc 

MAIN := $(BDIR)/boa
OBJS := $(ODIR)/ast.cmo $(ODIR)/lexer.cmo $(ODIR)/parser.cmo $(ODIR)/pprint.cmo $(ODIR)/eval.cmo $(ODIR)/check.cmo $(ODIR)/main.cmo

$(ODIR)/%.cmo: $(SDIR)/%.ml
	$(CAMLF) -package $(PKGS) -I $(ODIR)/ -c $< -o $@

$(ODIR)/%.cmi: $(SDIR)/%.mli
	$(CAMLF) -package $(PKGS) -I $(ODIR)/ -c $< -o $@

$(MAIN): $(OBJS)
	$(CAMLF) -linkpkg -package $(PKGS) -o $@ $^

$(SDIR)/lexer.ml: $(SDIR)/lexer.mll
	ocamllex -q $<

$(SDIR)/parser.ml: $(SDIR)/parser.mly
	$(CAMLYACC) -v $<

$(SDIR)/parser.mli: $(SDIR)/parser.mly
	$(CAMLYACC) -v $<

.PHONY: clean
clean:
	rm -f $(ODIR)/*.cmo $(ODIR)/*.cmi $(SDIR)/lexer.ml $(SDIR)/parser.ml $(SDIR)/parser.mli $(MAIN)

.PHONY: test
demo: $(MAIN)
	sh tests.sh 1> demo.out.md 2>&1
	
# Dependencies generated by `ocamldep -bytecode *.mli *.ml`.
$(ODIR)/ast.cmo :
$(ODIR)/check.cmo : $(ODIR)/ast.cmo
$(ODIR)/eval.cmo : $(ODIR)/ast.cmo $(ODIR)/pprint.cmo
$(ODIR)/lexer.cmo : $(ODIR)/parser.cmi 
$(ODIR)/main.cmo : $(ODIR)/pprint.cmo $(ODIR)/parser.cmi $(ODIR)/lexer.cmo $(ODIR)/eval.cmo $(ODIR)/check.cmo $(ODIR)/ast.cmo
$(ODIR)/parser.cmo : $(ODIR)/ast.cmo $(ODIR)/parser.cmi
$(ODIR)/parser.cmi : $(ODIR)/ast.cmo
$(ODIR)/pprint.cmo : $(ODIR)/ast.cmo